#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#--------------------------------------------------------------------------------
# ADDED BY AMIT FROM HERE ->
#--------------------------------------------------------------------------------

# LANG in .zprofile
# EDITOR in .zprofile
# Paths in .zprofile

#--------------------------------------------------------------------------------
# Android
export NDKROOT="/usr/local/Cellar/android-ndk/r8e"

#--------------------------------------------------------------------------------
# Configuration

# vi-mode
bindkey -v

# used to use alt+up but this is something to start with
bindkey '\e.' insert-last-word

#--------------------------------------------------------------------------------
# Google cloud util
# The next line updates PATH for the Google Cloud SDK.
source '/usr/local/google-cloud-sdk/path.zsh.inc'
#
# The next line enables bash completion for gcloud.
source '/usr/local/google-cloud-sdk/completion.zsh.inc'

#--------------------------------------------------------------------------------
# z - smart cd
. `brew --prefix`/etc/profile.d/z.sh
